module.exports = {
  products: [
    {
      productId: '000001',
      key: 1,
      src: '/assets/images/product-list-1.jpeg',
      url: '/pages/product/index?productId=000001',
      productName: '生活用品--脸盆',
      price: 1500,
      distribution: '快递',
      inventory: 120
    }, {
      key: 2,
      src: '/assets/images/product-list-2.jpeg',
      url: '/pages/product/index?productId=000002',
      productName: '生活用品--纸巾',
      price: 1000,
      productId: '000002',
      distribution: '快递',
      inventory: 120
    }, {
      key: 3,
      src: '/assets/images/product-list-3.jpeg',
      url: '/pages/product/index?productId=000003',
      productName: '生活用品--炒锅',
      price: 500,
      productId: '000003',
      distribution: '快递',
      inventory: 120
    }, {
      key: 4,
      src: '/assets/images/product-list-4.jpeg',
      url: '/pages/product/index?productId=000004',
      productName: '生活用品--脸盆',
      price: 1200,
      productId: '000004',
      distribution: '快递',
      inventory: 120
    }, {
      key: 5,
      src: '/assets/images/product-list-5.jpeg',
      url: '/pages/product/index?productId=000005',
      productName: '生活用品--砂锅',
      price: 1200,
      productId: '000005'
    }, {
      key: 6,
      src: '/assets/images/product-list-6.jpeg',
      url: '/pages/product/index?productId=000006',
      productName: '生活用品--脸盆',
      price: 3500,
      productId: '000006',
      distribution: '快递',
      inventory: 120
    }, {
      key: 7,
      src: '/assets/images/product-list-7.jpeg',
      url: '/pages/product/index?productId=000007',
      productName: '生活用品--高压锅',
      price: 2040,
      productId: '000007',
      distribution: '快递',
      inventory: 120
    }, {
      key: 8,
      src: '/assets/images/product-list-8.jpeg',
      url: '/pages/product/index?productId=000008',
      productName: '生活用品--脸盆',
      price: 4500,
      productId: '000008',
      distribution: '快递',
      inventory: 120
    }, {
      key: 9,
      src: '/assets/images/product-list-9.jpeg',
      url: '/pages/product/index?productId=000009',
      productName: '生活用品--脸盆',
      price: 3000,
      productId: '000009',
      distribution: '快递',
      inventory: 120
    }, {
      key: 10,
      src: '/assets/images/product-list-10.jpeg',
      url: '/pages/product/index?productId=0000010',
      productName: '生活用品--铁盆',
      price: 3000,
      productId: '0000010',
      distribution: '快递',
      inventory: 120
    }, {
      key: 11,
      src: '/assets/images/product-list-11.jpeg',
      url: '/pages/product/index?productId=0000011',
      productName: '生活用品--银盆',
      price: 3000,
      productId: '0000011',
      distribution: '快递',
      inventory: 120
    }
  ]
}